name: Deploy Lambda Monorepo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    # 変更があった関数のみを特定し、マトリックスとして設定
    strategy:
      matrix:
        # このステップで、git diff-treeなどを使って変更されたディレクトリを特定し、
        # 配列として出力するスクリプトを記述します。
        # 例: ['lambda-hello', 'lambda-goodbye']
        function: ${{ fromJson(needs.changed_functions.outputs.functions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ${{ matrix.function }} to Lambda
        working-directory: ./packages/${{ matrix.function }}
        run: |
          # 各関数のディレクトリに移動してzipファイルを作成
          zip -r deployment_package.zip .
          aws lambda update-function-code --function-name ${{ matrix.function }} --zip-file fileb://deployment_package.zip